# Official nginx:alpine image from Docker Hub - 31 October 2025
FROM nginx@sha256:eb212fe30b5b70a2ba09a0e3a1db07aea232fda6a6046a2bbf40c7203d3d5745

# Copy main nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the default server template for envsubst
COPY default.conf.template /etc/nginx/templates/default.conf.template
