#!/bin/sh

set -euo pipefail

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 <db> <cache> <queue> <sessions>" >&2
  exit 1
fi

DB_OPTION="$1"
CACHE_OPTION="$2"
QUEUE_OPTION="$3"
SESSION_OPTION="$4"

COMBO_NAME="${DB_OPTION}-${CACHE_OPTION}-${QUEUE_OPTION}-${SESSION_OPTION}"
OUTPUT_PATH="docker/img_laravel/.env"
PRESETS_ROOT="docker/scripts/laravel-env-presets"

append_fragment() {
  FRAGMENT_PATH="$1"

  if [ ! -f "$FRAGMENT_PATH" ]; then
    echo "Missing Laravel env fragment: ${FRAGMENT_PATH}" >&2
    exit 1
  fi

  cat "$FRAGMENT_PATH" >> "$OUTPUT_PATH"
  printf "\n" >> "$OUTPUT_PATH"
}

rm -f "$OUTPUT_PATH"

cat <<EOF >> "$OUTPUT_PATH"
# ------------------------------------------------------------------
# Autogenerated by docker/scripts/build_laravel_env.sh
# Combination: ${COMBO_NAME}
# ------------------------------------------------------------------

EOF

# Determine which Redis preset to use (if any component uses Redis)
REDIS_PRESET="none"
if [ "$CACHE_OPTION" = "redis" ] || [ "$QUEUE_OPTION" = "redis" ] || [ "$SESSION_OPTION" = "redis" ]; then
  REDIS_PRESET="base"
fi

# Build in the exact order of the example file
append_fragment "${PRESETS_ROOT}/app/base.env"
printf "\n" >> "$OUTPUT_PATH"
append_fragment "${PRESETS_ROOT}/app-maintenance/base.env"
printf "\n" >> "$OUTPUT_PATH"
append_fragment "${PRESETS_ROOT}/php-cli/base.env"
printf "\n" >> "$OUTPUT_PATH"
append_fragment "${PRESETS_ROOT}/bcrypt/base.env"
printf "\n" >> "$OUTPUT_PATH"
append_fragment "${PRESETS_ROOT}/log/base.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/db/${DB_OPTION}.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/session/${SESSION_OPTION}.env"
append_fragment "${PRESETS_ROOT}/session/base.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/broadcast/base.env"
append_fragment "${PRESETS_ROOT}/filesystem/base.env"

append_fragment "${PRESETS_ROOT}/queue/${QUEUE_OPTION}.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/cache/${CACHE_OPTION}.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/memcached/base.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/redis/${REDIS_PRESET}.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/mail/base.env"
printf "\n" >> "$OUTPUT_PATH"

append_fragment "${PRESETS_ROOT}/vite/base.env"

echo "Generated ${OUTPUT_PATH}"

