#!/bin/sh

set -euo pipefail

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 <db> <cache> <queue> <sessions>" >&2
  exit 1
fi

DB_OPTION="$1"
CACHE_OPTION="$2"
QUEUE_OPTION="$3"
SESSION_OPTION="$4"

COMBO_NAME="${DB_OPTION}-${CACHE_OPTION}-${QUEUE_OPTION}-${SESSION_OPTION}"
OUTPUT_PATH="docker/.env"
PRESETS_ROOT="docker/scripts/docker-compose-env-presets"

append_fragment() {
  FRAGMENT_PATH="$1"

  if [ ! -f "$FRAGMENT_PATH" ]; then
    echo "Missing env fragment: ${FRAGMENT_PATH}" >&2
    exit 1
  fi

  cat "$FRAGMENT_PATH" >> "$OUTPUT_PATH"
  printf "\n" >> "$OUTPUT_PATH"
}

rm -f "$OUTPUT_PATH"

cat <<EOF >> "$OUTPUT_PATH"
# ------------------------------------------------------------------
# Autogenerated by docker/scripts/build_compose_env.sh
# Combination: ${COMBO_NAME}
# ------------------------------------------------------------------
ENV_FILE=.env.${COMBO_NAME}

EOF

append_fragment "${PRESETS_ROOT}/base.env"
append_fragment "${PRESETS_ROOT}/db/${DB_OPTION}.env"
append_fragment "${PRESETS_ROOT}/cache/${CACHE_OPTION}.env"
append_fragment "${PRESETS_ROOT}/queue/${QUEUE_OPTION}.env"
append_fragment "${PRESETS_ROOT}/session/${SESSION_OPTION}.env"

echo "Generated ${OUTPUT_PATH}"

